export const ORG_NAME = "CNAC MURIMA W'ISANGI";

export type FieldType = "text" | "number" | "date" | "textarea" | "select" | "ref" | "file";

export type Field = {
  name: string;
  label: string;
  type: FieldType;
  list?: boolean;
  required?: boolean;
  options?: string[];
  refModule?: string;
  suffix?: string;
  section?: string;
  form?: boolean;
  /** Filtre les options par héritage : l'option doit partager la valeur `via`
   * de l'enregistrement sélectionné dans le champ `field`. */
  filterBy?: { field: string; via: string; match?: string };
};

export type ModuleDef = {
  slug: string;
  table: string;
  title: string;
  singular: string;
  description: string;
  group: string;
  labelField: string;
  labelField2?: string;
  filters?: Record<string, string | boolean>;
  fixedValues?: Record<string, unknown>;
  storageBucket?: string;
  fileSizeLimitMb?: number;
  fields: Field[];
};

const STATUT = (options: string[]): Field => ({
  name: "statut",
  label: "Statut",
  type: "select",
  list: true,
  options,
});

export const MODULES: ModuleDef[] = [
  {
    slug: "departements",
    table: "departements",
    title: "Départements",
    singular: "Département",
    description: "Niveau 1 de la structure : les grands départements de l'organisation.",
    group: "Administration / RH",
    labelField: "nom",
    fields: [
      { name: "nom", label: "Nom du département", type: "text", list: true, required: true },
      { name: "code", label: "Code", type: "text", list: true },
      { name: "description", label: "Description", type: "textarea" },
      STATUT(["Actif", "Inactif"]),
    ],
  },
  {
    slug: "fonctions",
    table: "fonctions",
    title: "Fonctions",
    singular: "Fonction",
    description: "Niveau 2 : une fonction appartient à un département.",
    group: "Administration / RH",
    labelField: "nom",
    fields: [
      { name: "nom", label: "Nom de la fonction", type: "text", list: true, required: true },
      {
        name: "departement_id",
        label: "Département",
        type: "ref",
        refModule: "departements",
        list: true,
        required: true,
      },
      { name: "description", label: "Description", type: "textarea" },
      STATUT(["Actif", "Inactif"]),
    ],
  },
  {
    slug: "profils",
    table: "profils",
    title: "Profils",
    singular: "Profil",
    description:
      "Niveau 3 : un profil appartient à une fonction (exemple : Administration > Finances > Comptable).",
    group: "Administration / RH",
    labelField: "nom",
    fields: [
      { name: "nom", label: "Nom du profil", type: "text", list: true, required: true },
      {
        name: "fonction_id",
        label: "Fonction",
        type: "ref",
        refModule: "fonctions",
        list: true,
        required: true,
      },
      { name: "description", label: "Description", type: "textarea" },
      STATUT(["Actif", "Inactif"]),
    ],
  },
  {
    slug: "employes",
    table: "employes",
    title: "Employés",
    singular: "Employé",
    description: "Dossiers complets du personnel permanent et non permanent.",
    group: "Administration / RH",
    labelField: "nom",
    labelField2: "prenom",
    fields: [
      { name: "matricule", label: "Matricule", type: "text", list: true, section: "Identité et contact" },
      { name: "nom", label: "Nom", type: "text", list: true, required: true, section: "Identité et contact" },
      { name: "prenom", label: "Prénom", type: "text", list: true, section: "Identité et contact" },
      { name: "telephone", label: "Téléphone", type: "text", list: true, section: "Identité et contact" },
      { name: "email", label: "E-mail de connexion", type: "text", section: "Identité et contact" },
      { name: "cni", label: "CNI", type: "text", section: "Identité et contact" },
      { name: "localite", label: "Adresse / localité", type: "text", section: "Identité et contact" },
      { name: "categorie_personnel", label: "Catégorie", type: "select", list: true, required: true, options: ["Permanent", "Non permanent"], section: "Affectation" },
      { name: "niveau_etudes", label: "Niveau d'études", type: "select", options: ["Humanités Générales", "Baccalauréat", "Maitrise", "Doctorat", "Primaire", "Secondaire", "Prefesseur"], section: "Affectation" },
      { name: "departement_id", label: "Département", type: "ref", refModule: "departements", list: true, section: "Affectation" },
      { name: "fonction_id", label: "Fonction", type: "ref", refModule: "fonctions", list: true, section: "Affectation", filterBy: { field: "departement_id", via: "id", match: "departement_id" } },
      { name: "profil_id", label: "Profil", type: "ref", refModule: "profils", list: true, section: "Affectation", filterBy: { field: "fonction_id", via: "id", match: "fonction_id" } },
      { name: "responsable", label: "Responsable", type: "select", options: ["Oui", "Non"], section: "Affectation" },
      { name: "date_entree", label: "Date d'entrée", type: "date", section: "Affectation" },
      { name: "date_sortie", label: "Date de sortie", type: "date", section: "Affectation" },
      { ...STATUT(["Disponible", "En congé", "En formation", "Inactif"]), section: "Affectation" },
      { name: "banque", label: "Banque", type: "text", section: "Informations bancaires" },
      { name: "numero_compte", label: "Numéro de compte", type: "text", section: "Informations bancaires" },
      { name: "contrat_path", label: "Contrat", type: "file", section: "Contrat et dossier" },
      { name: "dossier_path", label: "Dossier administratif", type: "file", section: "Contrat et dossier" },
    ],
  },
  {
    slug: "conges",
    table: "conges",
    title: "Congés",
    singular: "Congé",
    description: "Demandes et validations de congés du personnel.",
    group: "Administration / RH",
    labelField: "type_conge",
    fields: [
      { name: "employe_id", label: "Employé", type: "ref", refModule: "employes", list: true },
      {
        name: "type_conge",
        label: "Type de congé",
        type: "select",
        list: true,
        required: true,
        options: ["Annuel", "Maladie", "Maternité", "Circonstanciel", "Sans solde"],
      },
      { name: "date_debut", label: "Début", type: "date", list: true },
      { name: "date_fin", label: "Fin", type: "date", list: true },
      { name: "nombre_jours", label: "Nombre de jours", type: "number", list: true },
      { name: "motif", label: "Motif", type: "textarea" },
      STATUT(["En attente", "Approuvé", "Refusé"]),
    ],
  },
  {
    slug: "presences",
    table: "presences",
    title: "Présences",
    singular: "Présence",
    description: "Pointage quotidien des agents.",
    group: "Administration / RH",
    labelField: "date_presence",
    fields: [
      { name: "employe_id", label: "Employé", type: "ref", refModule: "employes", list: true },
      { name: "date_presence", label: "Date", type: "date", list: true, required: true },
      { name: "heure_arrivee", label: "Arrivée", type: "text", list: true },
      { name: "heure_depart", label: "Départ", type: "text", list: true },
      STATUT(["Présent", "Absent", "Retard", "Mission"]),
      { name: "observation", label: "Observation", type: "textarea" },
    ],
  },
  {
    slug: "salaires",
    table: "salaires",
    title: "Salaires",
    singular: "Bulletin de salaire",
    description: "Paramétrage, calculs détaillés et fiches mensuelles de paie.",
    group: "Administration / RH",
    labelField: "salaire_base",
    fields: [
      { name: "employe_id", label: "Employé", type: "ref", refModule: "employes", list: true },
      { name: "etat_civil", label: "État civil", type: "select", options: ["Célibataire", "Marié(e)"] },
      { name: "nombre_enfants", label: "Nombre d’enfants", type: "number" },
      { name: "salaire_base", label: "Salaire de base", type: "number", list: true, suffix: "FBu" },
    ],
  },
  {
    slug: "clients",
    table: "clients",
    title: "Clients",
    singular: "Client",
    description: "Répertoire des clients et bénéficiaires facturés.",
    group: "Données commerciales",
    labelField: "nom",
    fields: [
      { name: "nom", label: "Nom / Raison sociale", type: "text", list: true, required: true },
      { name: "contact", label: "Personne de contact", type: "text", list: true },
      { name: "telephone", label: "Téléphone", type: "text", list: true },
      { name: "email", label: "E-mail", type: "text" },
      { name: "adresse", label: "Adresse", type: "text", list: true },
      { name: "categorie", label: "Catégorie", type: "text" },
      STATUT(["Actif", "Inactif"]),
    ],
  },
  {
    slug: "fournisseurs",
    table: "fournisseurs",
    title: "Fournisseurs",
    singular: "Fournisseur",
    description: "Répertoire des fournisseurs et prestataires.",
    group: "Données commerciales",
    labelField: "nom",
    fields: [
      { name: "nom", label: "Nom / Raison sociale", type: "text", list: true, required: true },
      { name: "contact", label: "Personne de contact", type: "text", list: true },
      { name: "telephone", label: "Téléphone", type: "text", list: true },
      { name: "email", label: "E-mail", type: "text" },
      { name: "adresse", label: "Adresse", type: "text" },
      { name: "domaine", label: "Domaine", type: "text", list: true },
      STATUT(["Actif", "Inactif"]),
    ],
  },
  {
    slug: "achats",
    table: "achats",
    title: "Achats",
    singular: "Achat",
    description: "Commandes et acquisitions auprès des fournisseurs.",
    group: "Données commerciales",
    labelField: "reference",
    fields: [
      { name: "reference", label: "Référence", type: "text", list: true, required: true },
      {
        name: "fournisseur_id",
        label: "Fournisseur",
        type: "ref",
        refModule: "fournisseurs",
        list: true,
      },
      { name: "designation", label: "Désignation", type: "text", list: true },
      { name: "date_achat", label: "Date", type: "date", list: true, required: true },
      { name: "quantite", label: "Quantité", type: "number", list: true },
      { name: "montant", label: "Montant", type: "number", list: true },
      STATUT(["Commandé", "Reçu", "Payé", "Annulé"]),
    ],
  },
  {
    slug: "ventes",
    table: "ventes",
    title: "Ventes",
    singular: "Vente",
    description: "Ventes et facturations aux clients.",
    group: "Données commerciales",
    labelField: "reference",
    fields: [
      { name: "reference", label: "Référence", type: "text", list: true, required: true },
      { name: "client_id", label: "Client", type: "ref", refModule: "clients", list: true },
      { name: "designation", label: "Désignation", type: "text", list: true },
      { name: "date_vente", label: "Date", type: "date", list: true, required: true },
      { name: "quantite", label: "Quantité", type: "number", list: true },
      { name: "montant", label: "Montant", type: "number", list: true },
      STATUT(["Facturé", "Payé", "Annulé"]),
    ],
  },
  {
    slug: "budgets",
    table: "budgets",
    title: "Budgets",
    singular: "Ligne budgétaire",
    description: "Prévisions et réalisations budgétaires par exercice.",
    group: "Données commerciales",
    labelField: "intitule",
    fields: [
      { name: "intitule", label: "Intitulé", type: "text", list: true, required: true },
      { name: "exercice", label: "Exercice", type: "text", list: true, required: true },
      { name: "categorie", label: "Catégorie", type: "text", list: true },
      { name: "service", label: "Service", type: "text" },
      { name: "montant_prevu", label: "Montant prévu", type: "number", list: true },
      { name: "montant_realise", label: "Montant réalisé", type: "number", list: true },
      STATUT(["Ouvert", "Clôturé"]),
    ],
  },
  {
    slug: "articles",
    table: "articles",
    title: "Articles",
    singular: "Article",
    description: "Catalogue des articles en magasin avec seuils d'alerte.",
    group: "Stock",
    labelField: "designation",
    fields: [
      { name: "code", label: "Code", type: "text", list: true },
      { name: "designation", label: "Désignation", type: "text", list: true, required: true },
      { name: "categorie", label: "Catégorie", type: "text", list: true },
      { name: "unite", label: "Unité", type: "text" },
      { name: "prix_unitaire", label: "Prix unitaire", type: "number", list: true },
      { name: "quantite_stock", label: "Quantité en stock", type: "number", list: true },
      { name: "seuil_alerte", label: "Seuil d'alerte", type: "number", list: true },
      { name: "magasin", label: "Magasin / Dépôt", type: "text", list: true },
    ],
  },
  {
    slug: "mouvements_stock",
    table: "mouvements_stock",
    title: "Mouvements de stock",
    singular: "Mouvement",
    description: "Entrées et sorties de magasin.",
    group: "Stock",
    labelField: "reference",
    fields: [
      { name: "article_id", label: "Article", type: "ref", refModule: "articles", list: true },
      {
        name: "type_mouvement",
        label: "Type",
        type: "select",
        list: true,
        required: true,
        options: ["Entrée", "Sortie", "Ajustement"],
      },
      { name: "quantite", label: "Quantité", type: "number", list: true },
      { name: "date_mouvement", label: "Date", type: "date", list: true, required: true },
      { name: "service", label: "Service", type: "text", list: true },
      { name: "motif", label: "Motif", type: "textarea" },
      { name: "reference", label: "Référence", type: "text" },
    ],
  },
  {
    slug: "vehicules",
    table: "vehicules",
    title: "Véhicules",
    singular: "Véhicule",
    description: "Parc automobile : affectation, chauffeur et kilométrage.",
    group: "Charroi",
    labelField: "immatriculation",
    labelField2: "marque",
    fields: [
      { name: "immatriculation", label: "Immatriculation", type: "text", list: true, required: true },
      { name: "marque", label: "Marque", type: "text", list: true },
      { name: "modele", label: "Modèle", type: "text", list: true },
      { name: "type_vehicule", label: "Type", type: "text", list: true },
      { name: "affectation", label: "Affectation", type: "text", list: true },
      { name: "chauffeur", label: "Chauffeur", type: "text", list: true },
      { name: "kilometrage", label: "Kilométrage", type: "number", list: true, suffix: "km" },
      STATUT(["En service", "En entretien", "Immobilisé", "Réformé"]),
    ],
  },
  {
    slug: "carburant",
    table: "carburant",
    title: "Carburant",
    singular: "Bon de carburant",
    description: "Servis de carburant par véhicule et par station.",
    group: "Charroi",
    labelField: "bon",
    fields: [
      { name: "vehicule_id", label: "Véhicule", type: "ref", refModule: "vehicules", list: true },
      { name: "date_service", label: "Date", type: "date", list: true, required: true },
      { name: "litres", label: "Litres", type: "number", list: true, suffix: "L" },
      { name: "prix_total", label: "Montant", type: "number", list: true },
      { name: "kilometrage", label: "Kilométrage", type: "number", list: true, suffix: "km" },
      { name: "station", label: "Station / Dépôt", type: "text", list: true },
      { name: "bon", label: "N° de bon", type: "text", list: true },
    ],
  },
  {
    slug: "entretiens",
    table: "entretiens",
    title: "Entretiens",
    singular: "Entretien",
    description: "Maintenance et réparations du charroi.",
    group: "Charroi",
    labelField: "nature",
    fields: [
      { name: "vehicule_id", label: "Véhicule", type: "ref", refModule: "vehicules", list: true },
      { name: "date_entretien", label: "Date", type: "date", list: true, required: true },
      { name: "nature", label: "Nature", type: "text", list: true },
      { name: "garage", label: "Garage", type: "text", list: true },
      { name: "cout", label: "Coût", type: "number", list: true },
      STATUT(["Planifié", "En cours", "Terminé"]),
    ],
  },
  {
    slug: "federations",
    table: "federations",
    title: "1. Fédérations",
    singular: "Fédération",
    description: "Niveau 1 : une fédération par province. Créée par l'administration.",
    group: "Communauté",
    labelField: "nom",
    fields: [
      { name: "nom", label: "Nom", type: "text", list: true, required: true },
      {
        name: "province_id",
        label: "Province",
        type: "ref",
        refModule: "provinces",
        list: true,
        required: true,
      },
      { name: "email", label: "E-mail de connexion", type: "text", list: true, required: true },
      { name: "telephone", label: "Téléphone", type: "text", list: true },
      { name: "responsable_id", label: "Responsable", type: "ref", refModule: "employes" },
      { name: "contact", label: "Contact", type: "text", list: true },
      { name: "date_creation", label: "Date de création", type: "date", list: true },
      STATUT(["Actif", "Inactif"]),
    ],
  },
  {
    slug: "unions",
    table: "unions",
    title: "2. Unions",
    singular: "Union",
    description:
      "Niveau 2 : une union est créée par sa fédération et se situe dans une commune de la province de cette fédération.",
    group: "Communauté",
    labelField: "nom",
    fields: [
      { name: "nom", label: "Nom", type: "text", list: true, required: true },
      {
        name: "federation_id",
        label: "Fédération",
        type: "ref",
        refModule: "federations",
        list: true,
        required: true,
      },
      {
        name: "commune_id",
        label: "Commune",
        type: "ref",
        refModule: "communes",
        list: true,
        filterBy: { field: "federation_id", via: "province_id" },
      },
      { name: "email", label: "E-mail de connexion", type: "text", list: true, required: true },
      { name: "telephone", label: "Téléphone", type: "text", list: true },
      { name: "responsable_id", label: "Responsable", type: "ref", refModule: "employes" },
      { name: "contact", label: "Contact", type: "text", list: true },
      { name: "date_creation", label: "Date de création", type: "date", list: true },
      STATUT(["Actif", "Inactif"]),
    ],
  },
  {
    slug: "cooperatives",
    table: "cooperatives",
    title: "3. Coopératives",
    singular: "Coopérative",
    description:
      "Niveau 3 : une coopérative est créée par son union et se situe dans une zone de la commune de cette union.",
    group: "Communauté",
    labelField: "nom",
    fields: [
      { name: "nom", label: "Nom", type: "text", list: true, required: true },
      {
        name: "union_id",
        label: "Union",
        type: "ref",
        refModule: "unions",
        list: true,
        required: true,
      },
      {
        name: "zone_id",
        label: "Zone",
        type: "ref",
        refModule: "zones",
        list: true,
        filterBy: { field: "union_id", via: "commune_id" },
      },
      { name: "email", label: "E-mail de connexion", type: "text", list: true, required: true },
      { name: "telephone", label: "Téléphone", type: "text", list: true },
      { name: "responsable_id", label: "Responsable", type: "ref", refModule: "employes" },
      { name: "contact", label: "Contact", type: "text", list: true },
      { name: "date_creation", label: "Date de création", type: "date", list: true },
      STATUT(["Actif", "Inactif"]),
    ],
  },
  {
    slug: "associations",
    table: "associations",
    title: "4. Associations",
    singular: "Association",
    description:
      "Niveau 4 : une association est créée par sa coopérative et se situe sur une colline de la zone de cette coopérative.",
    group: "Communauté",
    labelField: "nom",
    fields: [
      { name: "nom", label: "Nom", type: "text", list: true, required: true },
      {
        name: "cooperative_id",
        label: "Coopérative",
        type: "ref",
        refModule: "cooperatives",
        list: true,
        required: true,
      },
      {
        name: "colline_id",
        label: "Colline",
        type: "ref",
        refModule: "collines",
        list: true,
        filterBy: { field: "cooperative_id", via: "zone_id" },
      },
      { name: "email", label: "E-mail de connexion", type: "text", list: true, required: true },
      { name: "telephone", label: "Téléphone", type: "text", list: true },
      { name: "responsable_id", label: "Responsable", type: "ref", refModule: "employes" },
      { name: "contact", label: "Contact", type: "text", list: true },
      { name: "date_creation", label: "Date de création", type: "date", list: true },
      STATUT(["Actif", "Inactif"]),
    ],
  },
  {
    slug: "membres",
    table: "membres",
    title: "5. Membres",
    singular: "Membre",
    description: "Niveau 5 : les membres sont créés par leur association et en héritent la colline.",
    group: "Communauté",
    labelField: "nom",
    labelField2: "prenom",
    fields: [
      { name: "nom", label: "Nom", type: "text", list: true, required: true },
      { name: "prenom", label: "Prénom", type: "text", list: true },
      {
        name: "association_id",
        label: "Association",
        type: "ref",
        refModule: "associations",
        list: true,
        required: true,
      },
      {
        name: "sexe",
        label: "Sexe",
        type: "select",
        list: true,
        options: ["Masculin", "Féminin"],
      },
      { name: "contact", label: "Contact", type: "text", list: true },
      { name: "superficie", label: "Superficie", type: "text" },
      { name: "nbre_plants", label: "Nombre de plants", type: "text" },
      { name: "date_naissance", label: "Date de naissance", type: "date" },
      { name: "date_adhesion", label: "Adhésion", type: "date", list: true },
      STATUT(["Actif", "Inactif"]),
    ],
  },
  {
    slug: "intervenants",
    table: "intervenants",
    title: "Intervenants",
    singular: "Intervenant",
    description: "Organisations intervenant au niveau provincial.",
    group: "Communauté",
    labelField: "nom",
    fields: [
      { name: "nom", label: "Nom", type: "text", list: true, required: true },
      { name: "province_id", label: "Province", type: "ref", refModule: "provinces", list: true },
      { name: "responsable_id", label: "Responsable", type: "ref", refModule: "employes" },
      { name: "contact", label: "Contact", type: "text", list: true },
      { name: "date_creation", label: "Date de création", type: "date", list: true },
      STATUT(["Actif", "Inactif"]),
    ],
  },
  {
    slug: "provinces",
    table: "provinces",
    title: "Provinces",
    singular: "Province",
    description: "Découpage administratif de premier niveau.",
    group: "Localisation",
    labelField: "nom",
    fields: [{ name: "nom", label: "Nom", type: "text", list: true, required: true }],
  },
  {
    slug: "communes",
    table: "communes",
    title: "Communes",
    singular: "Commune",
    description: "Communes rattachées à une province.",
    group: "Localisation",
    labelField: "nom",
    fields: [
      { name: "nom", label: "Nom", type: "text", list: true, required: true },
      { name: "province_id", label: "Province", type: "ref", refModule: "provinces", list: true },
    ],
  },
  {
    slug: "zones",
    table: "zones",
    title: "Zones",
    singular: "Zone",
    description: "Zones rattachées à une commune.",
    group: "Localisation",
    labelField: "nom",
    fields: [
      { name: "nom", label: "Nom", type: "text", list: true, required: true },
      { name: "commune_id", label: "Commune", type: "ref", refModule: "communes", list: true },
    ],
  },
  {
    slug: "collines",
    table: "collines",
    title: "Collines",
    singular: "Colline",
    description: "Collines rattachées à une zone.",
    group: "Localisation",
    labelField: "nom",
    fields: [
      { name: "nom", label: "Nom", type: "text", list: true, required: true },
      { name: "zone_id", label: "Zone", type: "ref", refModule: "zones", list: true },
    ],
  },
  {
    slug: "fiches-terrain",
    table: "fiches_terrain",
    title: "Fiches terrain",
    singular: "Fiche terrain",
    description:
      "Fiches envoyées par les agents de terrain via le formulaire public de collecte (/collecte).",
    group: "Communauté",
    labelField: "nom",
    labelField2: "prenom",
    fields: [
      { name: "nom", label: "Nom", type: "text", list: true, required: true },
      { name: "prenom", label: "Prénom", type: "text", list: true },
      { name: "province", label: "Province", type: "text", list: true },
      { name: "commune", label: "Commune", type: "text", list: true },
      { name: "zone", label: "Zone", type: "text" },
      { name: "colline", label: "Colline", type: "text" },
      { name: "federation", label: "Fédération", type: "text", list: true },
      { name: "union_nom", label: "Union", type: "text" },
      { name: "cooperative", label: "Coopérative", type: "text" },
      { name: "association", label: "Association", type: "text", list: true },
      { name: "telephone", label: "Téléphone", type: "text", list: true },
      { name: "date_adhesion", label: "Date d'adhésion", type: "date", list: true },
    ],
  },

  {
    slug: "imputations",
    table: "imputations",
    title: "Imputations",
    singular: "Imputation",
    description: "Plan comptable utilisé pour imputer les versements et les retraits.",
    group: "Finances & suivi",
    labelField: "code",
    labelField2: "description",
    fields: [
      { name: "code", label: "Code", type: "text", list: true, required: true },
      { name: "description", label: "Libellé du compte", type: "text", list: true, required: true },
      STATUT(["Actif", "Inactif"]),
    ],
  },
  {
    slug: "banque-versements",
    table: "livre_banque",
    title: "Versements bancaires",
    singular: "Versement",
    description: "Entrées enregistrées dans le livre de banque.",
    group: "Finances & suivi",
    labelField: "libelle",
    filters: { est_entree: true },
    fixedValues: { est_entree: true, credit: 0 },
    fields: [
      { name: "date_entree", label: "Date", type: "date", list: true, required: true },
      { name: "nom_operant", label: "Nom et prénom de l'opérant", type: "text", list: true },
      { name: "libelle", label: "Libellé", type: "text", list: true, required: true },
      {
        name: "imputation_id",
        label: "Compte (imputation)",
        type: "ref",
        refModule: "imputations",
        list: true,
        required: true,
      },
      { name: "debit", label: "Montant versé", type: "number", list: true, required: true, suffix: "FBu" },
      { name: "solde", label: "Solde", type: "number", list: true, form: false, suffix: "FBu" },
      STATUT(["Enregistrée", "Erronée"]),
    ],
  },
  {
    slug: "banque-retraits",
    table: "livre_banque",
    title: "Retraits bancaires",
    singular: "Retrait",
    description: "Sorties enregistrées dans le livre de banque.",
    group: "Finances & suivi",
    labelField: "libelle",
    filters: { est_entree: false },
    fixedValues: { est_entree: false, debit: 0 },
    fields: [
      { name: "date_entree", label: "Date", type: "date", list: true, required: true },
      { name: "nom_operant", label: "Nom et prénom de l'opérant", type: "text", list: true },
      { name: "libelle", label: "Libellé", type: "text", list: true, required: true },
      {
        name: "imputation_id",
        label: "Compte (imputation)",
        type: "ref",
        refModule: "imputations",
        list: true,
        required: true,
      },
      { name: "credit", label: "Montant retiré", type: "number", list: true, required: true, suffix: "FBu" },
      { name: "solde", label: "Solde", type: "number", list: true, form: false, suffix: "FBu" },
      STATUT(["Enregistrée", "Erronée"]),
    ],
  },

  {
    slug: "operations",
    table: "operations",
    title: "Caisse & opérations",
    singular: "Opération",
    description: "Entrées et sorties de caisse.",
    group: "Finances & suivi",
    labelField: "libelle",
    fields: [
      { name: "libelle", label: "Libellé", type: "text", list: true, required: true },
      {
        name: "type_operation",
        label: "Type",
        type: "select",
        list: true,
        required: true,
        options: ["Entrée", "Sortie"],
      },
      {
        name: "imputation_id",
        label: "Compte (imputation)",
        type: "ref",
        refModule: "imputations",
        list: true,
        required: true,
      },
      { name: "montant", label: "Montant", type: "number", list: true },
      { name: "date_operation", label: "Date", type: "date", list: true, required: true },
      { name: "beneficiaire", label: "Bénéficiaire", type: "text", list: true },
      STATUT(["En attente", "Validée", "Annulée"]),
    ],
  },
  {
    slug: "transactions_mobile",
    table: "transactions_mobile",
    title: "Mobile money",
    singular: "Transaction",
    description: "Opérations électroniques et mobile money.",
    group: "Finances & suivi",
    labelField: "reference",
    fields: [
      {
        name: "operateur",
        label: "Opérateur",
        type: "select",
        list: true,
        required: true,
        options: ["Lumicash", "Ecocash", "M-Pesa", "Airtel Money", "Autre"],
      },
      {
        name: "type_operation",
        label: "Type",
        type: "select",
        list: true,
        required: true,
        options: ["Dépôt", "Retrait", "Transfert", "Paiement"],
      },
      { name: "reference", label: "Référence", type: "text", list: true },
      { name: "telephone", label: "Téléphone", type: "text", list: true },
      { name: "montant", label: "Montant", type: "number", list: true },
      { name: "commission", label: "Commission", type: "number", list: true },
      { name: "date_operation", label: "Date", type: "date", list: true, required: true },
      { name: "agent", label: "Agent", type: "text" },
      STATUT(["Réussie", "En attente", "Échouée"]),
    ],
  },
  {
    slug: "programmes",
    table: "programmes",
    title: "Programmes",
    singular: "Programme",
    description: "Cadres institutionnels auxquels les projets sont rattachés.",
    group: "Projets & partenariats",
    labelField: "intitule",
    fields: [
      { name: "intitule", label: "Nom du programme", type: "text", list: true, required: true },
      { name: "objectifs", label: "Objectifs", type: "textarea", list: true, required: true },
      { name: "description", label: "Description", type: "textarea", list: true, required: true },
      STATUT(["À venir", "En cours", "Terminé", "Suspendu"]),
    ],
  },
  {
    slug: "partenaires",
    table: "partenaires",
    title: "Partenaires",
    singular: "Partenaire",
    description: "Organisations partenaires et objets de collaboration.",
    group: "Projets & partenariats",
    labelField: "nom",
    fields: [
      { name: "nom", label: "Nom du partenaire", type: "text", list: true, required: true },
      { name: "website_url", label: "Site web", type: "text", list: true },
      { name: "contact", label: "Contact / e-mail", type: "text", list: true, required: true },
      { name: "localisation", label: "Localisation", type: "text", list: true, required: true },
      { name: "objet_collaboration", label: "Objet de collaboration", type: "textarea", list: true, required: true },
      { name: "logo_path", label: "Logo", type: "file", list: true },
    ],
    storageBucket: "documents-projets",
    fileSizeLimitMb: 20,
  },
  {
    slug: "projets",
    table: "projets",
    title: "Projets",
    singular: "Projet",
    description: "Dossiers opérationnels rattachés à un programme et un partenaire.",
    group: "Projets & partenariats",
    labelField: "titre",
    fields: [
      { name: "titre", label: "Nom du projet", type: "text", list: true, required: true },
      {
        name: "programme_id",
        label: "Programme",
        type: "ref",
        refModule: "programmes",
        list: true,
      },
      {
        name: "partenaire_id",
        label: "Partenaire",
        type: "ref",
        refModule: "partenaires",
        list: true,
      },
      { name: "objectifs", label: "Objectifs", type: "textarea", required: true },
      { name: "description", label: "Description", type: "textarea", required: true },
      { name: "chef_projet_id", label: "Chef du projet", type: "ref", refModule: "employes", list: true, required: true },
      { name: "budget", label: "Budget initial", type: "number", list: true, required: true },
      { name: "budget_depense", label: "Budget engagé", type: "number", list: true, form: false },
      { name: "budget_restant", label: "Budget restant", type: "number", list: true, form: false },
      { name: "date_debut", label: "Date de début", type: "date", list: true, required: true },
      { name: "date_fin", label: "Date de fin", type: "date", list: true, required: true },
      { name: "fichier_path", label: "Document du projet", type: "file", list: true, required: true },
      STATUT(["À venir", "En cours", "Terminé", "Suspendu", "Clôturé"]),
    ],
    storageBucket: "documents-projets",
    fileSizeLimitMb: 20,
  },
  {
    slug: "dossiers-archives",
    table: "dossiers_archives",
    title: "Dossiers documentaires",
    singular: "Dossier documentaire",
    description: "Classement utilisé pour les archives et les documents de planification.",
    group: "Finances & suivi",
    labelField: "nom",
    fields: [
      { name: "nom", label: "Nom du dossier", type: "text", list: true, required: true },
    ],
  },
  {
    slug: "archives",
    table: "archives",
    title: "Archives",
    singular: "Document archivé",
    description: "Documents archivés, classés par dossier et conservés dans un espace privé.",
    group: "Finances & suivi",
    labelField: "titre",
    filters: { type_document: "Archive" },
    fixedValues: { type_document: "Archive" },
    storageBucket: "documents-archives",
    fileSizeLimitMb: 20,
    fields: [
      { name: "dossier_id", label: "Dossier d’archive", type: "ref", refModule: "dossiers-archives", list: true, required: true },
      { name: "titre", label: "Contenu de l’archive", type: "text", list: true, required: true },
      { name: "auteur_nom", label: "Auteur", type: "text", list: true, form: false },
      { name: "date_document", label: "Date", type: "date", list: true, form: false },
      { name: "fichier_path", label: "Document", type: "file", list: true, required: true },
    ],
  },
  {
    slug: "planifications",
    table: "archives",
    title: "Planification",
    singular: "Document de planification",
    description: "Plans et documents de programmation classés par type de document.",
    group: "Finances & suivi",
    labelField: "titre",
    filters: { type_document: "Planification" },
    fixedValues: { type_document: "Planification" },
    storageBucket: "documents-archives",
    fileSizeLimitMb: 20,
    fields: [
      { name: "dossier_id", label: "Type de document", type: "ref", refModule: "dossiers-archives", list: true, required: true },
      { name: "titre", label: "Titre du document", type: "text", list: true, required: true },
      { name: "auteur_nom", label: "Auteur", type: "text", list: true, form: false },
      { name: "date_document", label: "Date", type: "date", list: true, form: false },
      { name: "fichier_path", label: "Document", type: "file", list: true, required: true },
    ],
  },
];

export const MODULE_MAP: Record<string, ModuleDef> = Object.fromEntries(
  MODULES.map((m) => [m.slug, m]),
);

export const GROUPS = [
  "Administration / RH",
  "Communauté",
  "Localisation",
  "Données commerciales",
  "Stock",
  "Charroi",
  "Finances & suivi",
  "Projets & partenariats",
];

export function modulesOfGroup(group: string): ModuleDef[] {
  return MODULES.filter((m) => m.group === group);
}
