INSERT INTO public.imputations (code, description, statut)
SELECT v.code, v.description, 'Actif' FROM (VALUES
('073','Frais à recupérer'),
('10','Capital et assimilés'),
('101','Capital social'),
('102','Primes liées au capital social'),
('103','Capital personnel'),
('104','Comptes bloqués des établissements et succursales'),
('105','Fonds de dotation'),
('108','Compte de l''exploitant'),
('109','Associés, capital souscrit non libéré'),
('11','Réserves'),
('111','Réserves reglèmentaires'),
('112','Réserves facultatives'),
('116','Réserves consolidées'),
('117','Ecarts d''équivalence'),
('12','Résultat et report à nouveau'),
('120','Report à nouveau'),
('125','Résultat net de l''exercice'),
('13','Autres éléments de capitaux propres'),
('131','Ecarts de conversions'),
('132','Ecarts de réévaluation'),
('133','Ecarts d''évaluation'),
('138','Autres profits et pertes non comptabilisés en résultant'),
('14','Passifs non courants: Charges et produits différés'),
('141','Subventions d''équipements'),
('142','Autres subventions d''investissement'),
('143','Impôts différés actifs'),
('144','Impôts différés passifs'),
('148','Autres produits et charges différés'),
('15','Compte de liaison entre établissements et sociétés en participation'),
('151','Compte de liaison des établissements'),
('156','Biens et prestations des établissements'),
('157','Biens et prestations de services échangés entre établissements (produits)'),
('158','Comptes de liaison des sociétés en participation'),
('16','Emprunts obligatoire'),
('161','Emprunts état'),
('162','Emprunts émis auprès de public'),
('163','Emprunts bancaires ou assimilés'),
('164','Autres emprunts obligatoires'),
('17','Autres emprunts et dettes assimilés du passif non courant'),
('171','Dépôts et cautionnements reçus à plus d''un an'),
('172','Fournisseurs à plus d''un an'),
('173','Avances reçues et comptes bloqués à plus d''un an'),
('174','Avances de l''état à plus d''un an'),
('175','Emprunts à long et moyen terme'),
('176','Dettes rattachées à des participations'),
('178','Dette sur contrats de locations financements'),
('19','Provisions - Passifs non courants'),
('191','Provisions pour litiges en cours'),
('192','Provisions pour renouvellement des immobilisations'),
('194','Provisions pour les charges à partir ( pour pensions et obligations similaires)'),
('196','Provisions pour pensions et obligations similaires'),
('198','Autres Provisions'),
('20','Immobilisations incorporelles et assimilées'),
('201','Ecarts d''acquisition (ou goodwill)'),
('203','Frais de développement'),
('204','Logiciels informatiques'),
('205','Autres concessions, brevets, licences, marques et droits similaires'),
('206','Fonds de commerce et droits au bail'),
('208','Autres immobilisations incorporelles'),
('21','Terrains'),
('211','Terrains de construction et chantiers'),
('212','Terrains d''exploitations industrielle'),
('213','Terrains d''exploitations agricole'),
('219','Autres Terrains'),
('22','Autres immobilisations corporelles'),
('221','Constructions'),
('222','Travaux de mise en valeur des Terrains'),
('223','Travaux d''aménagement des plantations ( actifs biologiques)'),
('224','Mobiliers'),
('225','Machines et autres matériels'),
('2251','Matériels et outillages ou matériels de transport automobile (ex citernes)'),
('2256','Emballages récupérables (matériels de transport)'),
('226','Agencements, aménagement et installations'),
('227','Immobilisations animales (Actifs biologiques)'),
('229','Autres immobilisations corporelles'),
('23','Immobilisations corporelles en cours'),
('231','Immobilisations en cours de constructions'),
('232','Immobilisations en cours de route'),
('235','Autres immobilisations en cours'),
('24','Avancements et comptes versés sur commande d''immobilisations'),
('25','Prêts et autres créances à long et moyen terme'),
('251','Prêts à plus d''un an'),
('252','Avances consentise à plus d''un an'),
('253','Créances sur clients à plus d''un an et effets à recevoir à plus d''un an'),
('254','Dépôts et cautionnements à plus d''un an'),
('257','Intérêts courus non échus'),
('258','Créances sur contrat de location financement'),
('26','Titres et autres instruments financiers non courants'),
('261','Participation et créances rattachées'),
('263','Participations mise en équivalence'),
('265','Titres immobilisés financières'),
('269','Versements à effectuer sur titres non liberées'),
('28','Amortissements des immobilisations'),
('280','Amortissements sur immobilisations incorporelles'),
('281','Amortissements des terrains'),
('282','Amortissements des autres immobilisations corporelles'),
('285','Amortissements des immobilisations (ou des machines et autres matériels)'),
('287','Amortissements matériel de transports'),
('29','Dépréciations sur actifs non courants'),
('290','Dépréciation des immobilisations incorporelles'),
('291','Dépréciation des terrains'),
('292','Dépréciation des autres immobilisations corporelles'),
('293','Dépréciation des immobilisations corporelles en cours'),
('294','Dépréciation des avances et comptes sur commande d''immobilisation en cours'),
('295','Dépréciation des prêts et autres créances'),
('296','Dépréciation des participations (des titres)'),
('2961','Dépréciation des actions'),
('298','Dépréciation des autres actifs financiers non courants'),
('30','Marchandises'),
('31','Matières et fournitures'),
('311','Matières premières en stock'),
('315','Fournitures en stock'),
('3176','Fournitures et timbres de poste'),
('32','Déchets et produits de récupérations'),
('321','Déchets et rebus en stock'),
('325','Produits de récupération en stock'),
('33','Emballages commerciaux'),
('331','Emballage non récupérable en stock'),
('332','Emballage récupérable en stock'),
('333','Stock d''emballage mixte'),
('3352','Emballage récupérable consignés'),
('34','Produits semi-ouvrés'),
('35','Produits finis'),
('36','Produits et travaux en cours'),
('361','Produits en cours'),
('365','Travaux en cours'),
('37','Achats stockés et frais sur achats'),
('370','Achats de mise stockés'),
('371','Achats et frais sur achat matières et fournitures stockés'),
('372','Achats et frais sur achats déchets et rebuts stockés'),
('373','Achats et frais sur achats d''emballage commerciaux'),
('3731','Achats d''emballages récupérables'),
('3732','Achats d''emballage non récupérable'),
('3733','Achat d''emballage à usage mixte'),
('38','Stock en cours de routes, consignations ou à réceptionner'),
('381','Stock en cours de route'),
('382','Stock en consigantion'),
('383','Stock à réceptionner'),
('39','Dépréciation des stocks'),
('390','Dépréciation de mise stockée'),
('391','Dépréciation des matières de fournitures stockées'),
('392','Dépréciations des déchets et rebuts stockés'),
('393','Dépréciation des emballages commerciaux stockées'),
('394','Dépréciation des produits semi-ouvrés stockés'),
('395','Dépréciation des produits finis stockés'),
('396','Dépréciation et travaux en cours'),
('40','Fournisseur et comptes rattachés'),
('401','Fournisseurs ordinaires'),
('402','Fournisseurs d''immobilisations'),
('403','Fournisseurs état et collectivités publiques'),
('404','Fournisseurs - effets à payer'),
('405','Fournisseurs sociétés apparentées'),
('406','Fournisseurs, retenues de garanties'),
('407','Fournisseurs, factures à recevoir'),
('408','Fournisseurs débiteurs'),
('4082','Fournisseurs débruteurs'),
('4083','Fournisseurs, emballages et matériels consignés'),
('41','Clients'),
('411','Clients ordinaires'),
('412','Clients doutés'),
('413','Clients - état et collectives publiques'),
('414','Clients - effets à recevoir'),
('415','Clients - sociétés apparentées'),
('416','Clients - retenues de garanties'),
('417','Clients - factures à établir'),
('418','Clients créditeurs'),
('4182','Clients créditeurs (détail)'),
('4183','Clients, emballages et matériels consignés'),
('419','Autres clients'),
('42','Personnel'),
('421','Personnel, rémunération due'),
('422','Avances et comptes au personnel'),
('423','Oppositions sur traitements et salaires'),
('424','Délégation de salaires et d''appointements'),
('425','Compte courant du personnel'),
('429','Personnel, charges à payer et autres créances ou dettes'),
('43','Etat et autres collectivités publiques'),
('431','Etat, impôts sur les résultats'),
('432','Etat, impôts sur les résultats (autres)'),
('4325','Etat, impôt professionnelle sur les rémunérations des employés'),
('43271','TVA collecté'),
('43272','TVA déductible sur achat des biens et services'),
('433','Etat, impôts et taxes recouvrables sur des tiers'),
('434','Prêts et avances de l''Etat et autres collectivités publiques- passif courant'),
('435','Etat, subventions à recevoir'),
('437','Opérations particulières avec l''Etat, les collectivité publiques, les organismes internationaux'),
('44','Associés et sociétés apparentées'),
('443','Associés - dividendes à payer'),
('444','Associés - comptes courants'),
('445','Sociétés apparentées'),
('448','Opérations faites en commun ou en groupement'),
('45','Organismes sociaux'),
('451','INSS'),
('452','MFP (Pour les entreprises affiliées)'),
('46','Créditeurs et débiteurs divers'),
('462','Dépôts et cautionnements reçus à moins d''un an'),
('463','Dépôts et cautionnements versés à moins d''un an'),
('464','Parts à moins d''un an des emprunts et dettes LMT'),
('465','Parts à moins d''un an des prêts et créances LMT'),
('466','Créances sur cessions d''actifs'),
('467','Opérations effectuées pour le compte de tiers'),
('468','Autres créditeurs divers'),
('4681','Jetons de présences à payer'),
('4682','Tantièmes à payer'),
('469','Autres débruteurs divers'),
('47','Comptes de régularisations'),
('471','Comptes de regularisations actifs'),
('4711','Produits à recevoir'),
('475','Comptes de régularisation passif'),
('4751','Eau et électricité ou charges à constater'),
('47515','Assurances payées ou compte d''avances'),
('48','Comptes d''attente et transitoires'),
('49','Comptes sur créances de l''actif courant'),
('491','Provisions des créances'),
('52','Valeurs mobilières de l''actif circulant'),
('521','Part dans les entreprises liées'),
('523','Autres actions ou titres conférant un droit de propriété'),
('527','Instruments financiers dérivés'),
('528','Autres valeurs mobilières de placement et créances assimilées'),
('529','Versements restant à effectuer sur VMP non liberées'),
('53','Warrant à payer'),
('531','Effets à payer ( état de rapprochement)'),
('5311','Traites ou L.C à payer'),
('5312','B.O à payer'),
('532','Warrants à payer'),
('54','Warrants à recevoir'),
('541','Effets à recevoir moins d''un an'),
('5411','Lettres de change à recevoir'),
('5412','Billet à ordre à recevoir'),
('542','Warrants à recevoir moins d''un an'),
('55','Chèques et coupons à encaisser'),
('551','Chèques à encaisser'),
('552','Coupons échus à l''encaissement'),
('5526','Obligations, bons du trésor et bons de caisse à court terme'),
('553','Effets à l''encaissement'),
('554','Effets à l''escompte'),
('56','Banques, chèques postaux, comptes de régies d''avance et d''accréditifs'),
('561','Banques locales'),
('5611','Finbank'),
('5612','BANCOBU'),
('5614','COOPEC'),
('562','Organismes financiers locaux'),
('563','Chèques postaux'),
('564','Banques et organismes financiers à l''étranger'),
('565','Régies d''avances et accréditifs'),
('566','Crédits documentaires - Fonds bloqués'),
('567','Dépôts et cautionnements bancaire'),
('568','Compte à terme'),
('569','Autres concours bancaires'),
('57','Caisse'),
('571','Caisse principale'),
('572','Petites Caisses'),
('574','Caisse des établissements succursales'),
('58','Virements internes'),
('59','Dépréciations sur comptes financiers'),
('60','Coûts des stocks vendus'),
('601','Coût des marchandises vendues'),
('603','Coûts des emballages tiers non salariés'),
('609','Réductions obtenues sur marchandises'),
('61','Matières et fournitures consommées'),
('611','Matières premières consommées'),
('617','Fournitures consommés'),
('6171','Eau et éléctricité'),
('62','Transports consommés'),
('621','Transports sur vente'),
('622','Transports et déplacements tiers non salariées'),
('623','Transports et déplacement concernant le personnel'),
('624','Transports collectifs du personnel'),
('626','Litiges en cours'),
('628','Autres frais de transport et déplacement'),
('63','Autres services consommés'),
('631','Loyer et charges locatives'),
('632','Entretiens et réparations'),
('633','Honoraires et assimilés'),
('634','Achats de services extérieurs'),
('6345','Frais bancaires ou frais de représentation et de mission'),
('635','Commission et courtages sur vente'),
('636','Sous-traitance général'),
('637','Assurances'),
('638','Autres services consommés'),
('639','Rabais, remise, ristournes et escomptes obtenus'),
('64','Autres charges de gestion courante'),
('641','Redevances pour concessions, brevets, licences, marques, procédés, logiciels, droits et valeurs similaires'),
('642','Réparation'),
('643','Achat services extérieurs'),
('6432','Assurances payées'),
('6433','Assurance transport'),
('644','Rémunérations des administrateurs'),
('645','Dons, libéralité et subventions accordées, cotisations versées'),
('646','Moins - valeurs sur cessions d''actifs immobilisés'),
('647','Pertes sur créances irrécouvrables'),
('648','Quote - part de résultat sur opérations faites en commun'),
('649','Pertes diverses'),
('6492','Mali sur stock'),
('65','Charges de personnel'),
('651','Rémunérations directes'),
('6511','Salaires de base'),
('6512','Heures supplémentaires'),
('6513','Primes'),
('6514','Commissions'),
('652','Indemnités de logement'),
('653','Prestations familiales'),
('654','Charges sociales'),
('6541','INSS part patronale'),
('6542','MFP part patronale'),
('6543','Primes (charges sociales)'),
('6544','Frais pharmaceutiques, frais médicaux ou hospitaliers'),
('655','Indemnités de fin de contrat'),
('656','Autres avantages et indemnités au personnel'),
('66','Impôts, taxes et versements assimilés'),
('661','Impôts sur le revenus locatifs'),
('662','Impôts réels'),
('664','Impôts sur le revenus mobiliers'),
('668','Douanes et taxes assimilés'),
('669','Autres impôts et taxes'),
('67','Charges financières ou frais financiers (intérêt à payer)'),
('671','Pertes de change'),
('672','Ecart d''évaluation sur instruments financiers - moins -value'),
('673','Charges financières sur emprunts et dettes'),
('674','Intérêts bancaires sur opérations de financements'),
('677','Pertes sur créances liées à des participations'),
('678','Charges nettes sur cessions d''actifs financiers'),
('679','Autres charges financières'),
('68','Dotations aux amortissements, dépréciations et provisions'),
('681','Dotations aux amortissements des immobilisations corporelles et incorporelles'),
('682','Dotations aux dépréciations des immobilisations corporelles et incorporelles'),
('684','Dotations aux dépréciations des actifs circulants'),
('685','Dotations aux provisions d''exploitation'),
('686','Dotations aux provisions financières'),
('687','Dotations aux dépréciation des éléments financiers'),
('689','Dotations aux provisions'),
('69','Impôts sur les résultats et assimilés'),
('691','Impôts exigibles de la période'),
('697','Impôts différés payables'),
('699','Impôts différés récupération'),
('70','Ventes des marchandises'),
('701','Vente de marchandises'),
('703','Ventes d''emballages'),
('709','Réduction sur Vente'),
('71','Production vendue de biens et services'),
('711','Production industrielle vendue'),
('712','Production agricole vendue'),
('713','Production animale vendue'),
('715','Prestations des services ( y compris revenus locatifs)'),
('716','Boni sur emballages'),
('719','Réduction sur prestations de services'),
('72','Production stockée'),
('722','Déchets et rebuts'),
('723','Emballages commerciaux fabriqués par l''entreprise'),
('724','Produits sémi-ouvrés'),
('725','Produits finis'),
('726','Produits et travaux en cours'),
('73','Production immobilisée'),
('734','Produits nets partiels'),
('74','Produits et profits divers'),
('741','Redevances reçues pour concessions, brevets, licences, marques, procédés, logiciels, droits et valeurs similaires')
) AS v(code, description)
WHERE NOT EXISTS (SELECT 1 FROM public.imputations i WHERE i.code = v.code);